# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build for Android

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-last

    strategy:
            fail-fast: true

      
    steps:
    - uses: actions/checkout@v4

    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}


        name: Strip
        run: |
        cd src/main/cpp/build/
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libmobileglues.so
        
       
        name: Upload
        uses: actions/upload-artifact@v4
        with:
        name: MobileGlues
        path: src/main/cpp/build/libmobileglues.so

    
